import "./globals.css";
import Header from "./components/Header";
import Head from "next/head";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>Hulu 2.0</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className="bg-[#06202A] text-gray-300">
        <div>
           <Header/>
        </div>
        <div>
        {children}
        </div>
        </body>
    </html>
  );
}
